name: sila_app
description: صلة - تعارف - محادثة - صداقات
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  zego_uikit_prebuilt_call: ^4.8.0
flutter:
  uses-material-design: true
